### ISSUE TITLE
walker positions not changing in Parallel-Tempering Ensemble MCMC

### ISSUE THREAD

**Issue by tinapeters** [dfm/emcee#218] opened 2017-06-15 15:30 UTC
I construct the sampler object in the usual way: sampler=PTSampler(...) and then iterate over the generator. I am outputting the results of every 10th step to a text file, just for monitoring while testing by doing:

for i, result in enumerate(sampler.sample(position0, interations=1000)):
    position_new = result[0]
    lnprob_new = result[1]
    lnlike_new =  result[2]

This works fine when I use EnsembleSampler, but with PTSampler the position_new never changes. The lnlike_new and lnprob_new change whenever there is an accept and lnprob_new also changes when there is a temperature swap.

@farr @dfm

**Comment by tinapeters** [comment] 2017-06-20 20:42
I also tried running 'sampler.run_mcmc(position, nsteps)',  the printed each step of 'sampler.chain' and 'sampler.lnlikelihood' to a file. I got the same behavior, where the walker positions never change, but lnlikelihood will change whenever there is an accept and lnprob_new also changes when there is a temperature swap.

Has anyone else seen this?

**Comment by dfm** [comment] 2017-06-20 21:05
@farr: Any thoughts?

@tinapeters: Can you come up with a minimal example (i.e. no dependencies, etc.) that reproduces this behavior and post that code?

**Comment by dfm** [comment] 2017-07-11 20:26
@farr: here's an email from @tinapeters (06-26-2017). I'm not familiar enough with the PTSampler to debug what's going on. Can you take a look?

> [This](https://gist.github.com/dfm/af9a6d4420a696747f91852c6d45522b) is the closest I could get to a minimal example that reproduces this behavior. Lines 20, 21, and 22 are a subset of my data that I'm trying to fit, so you don't have to worry about loading the file.
> 
> When I run the example [here](http://dan.iel.fm/emcee/current/user/pt/) or run the attached code with ntemps = 1 I don't see the odd behavior I described earlier. However, when I run with ntemps > 1, I do.
>
> Hopefully, this helps us get to the bottom of it.

**Comment by dfm** [comment] 2017-11-06 20:48
I'm going to close this issue for now because I've made the executive decision to remove the PTSampler from the next release of emcee. I don't have the expertise or patience to maintain this part of the project. Sorry!

**Comment by dfm** [comment] 2017-11-06 20:49
You can check out https://github.com/willvousden/ptemcee for a more or less compatible implementation by people who actually know what they're doing!

**Closed by dfm** 2017-11-06 20:48 UTC
